# A more structured config.toml file for Supabase Edge Functions

[functions]
# Remove the port setting from here as it's causing parsing errors

[auth]
enabled = true

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
