
# This is a generic configuration file for Supabase Edge Functions

[functions]
serve = { port = 54321 }

[auth]
enabled = true

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
