// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgjtkmduelappimtorwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnanRrbWR1ZWxhcHBpbXRvcndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzOTQ1NTAsImV4cCI6MjA1NTk3MDU1MH0.4MT-8B_L86nFmGsrnDN612BIdL6gM1mrgenaFnbXHd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);